[package]
name = "stackable-airflow-operator"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Operator for Apache Airflow"
license = "OSL-3.0"
version = "0.0.0-dev"
edition = "2021"
repository = "https://github.com/stackabletech/airflow-operator"
publish = false

[dependencies]
anyhow = "1.0"
clap = "4.1"
fnv = "1.0"
futures = { version = "0.3", features = ["compat"] }
serde = "1.0"
snafu = "0.7"
stackable-airflow-crd = { path = "../crd" }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.40.2" }
strum = { version = "0.24", features = ["derive"] }
tokio = { version = "1.25", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"

[build-dependencies]
built = { version =  "0.5", features = ["chrono", "git2"] }
stackable-airflow-crd = { path = "../crd" }
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.40.2" }

[dev-dependencies]
serde_yaml = "0.8"
