= Troubleshooting

== S3 Logging: An error occurred (411) when calling the PutObject operation: Length Required

If Airflow is trying to access S3 (e.g. for remote task logging) and throws the following error

[source,text]
----
{s3_task_handler.py:190} ERROR - Could not write logs to s3://***/***-task-logs/dag_id=test/run_id=manual__2025-05-22T08:14:17.917519+00:00/task_id=extract/attempt=1.log
Traceback (most recent call last):
[..]
botocore.exceptions.ClientError: An error occurred (411) when calling the PutObject operation: Length Required
----

then this is an indication that your S3 store doesn't support the new AWS S3 checksums.
Ideally you should upgrade your S3 store to a more recent version that supports the new checksums (if there is any).
If this is not possible, you can work around this by setting the following env vars

[source,yaml]
----
webservers: # Also add to other roles!
  envOverrides:
    AWS_REQUEST_CHECKSUM_CALCULATION: when_required
    AWS_RESPONSE_CHECKSUM_VALIDATION: when_required
----

See e.g. https://github.com/minio/minio/issues/20845[this MinIO issue] for details.

== Setting API Workers

In Airflow the webserver (called the API Server in Airflow 3.x+) can use multiple workers.
This is determined by the environment variable `+AIRFLOW__API__WORKERS+` and is set by default to `4`.
For most cases the default should work without problem, but if you run into performance issues and would like to add more workers, you can either modulate multiple worker processes at the level of webserver, keeping the default value for each one:

[source,yaml]
----
webservers:
  roleGroups:
    default:
      replicas: 2 # add a replica (with the default number of workers)
----

or change the environment variable using `envOverrides`:

[source,yaml]
----
webservers:
  envOverrides:
    AIRFLOW__API__WORKERS: "6" # something other than the default
----

TIP: Our strong recommendation is to increase the webserver replicas, with each webserver running a single worker, as this removes the risk of running into timeouts or memory issues.
