---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 3.1.6
    pullPolicy: IfNotPresent
  clusterConfig:
    loadExamples: true
    exposeConfig: false
    credentialsSecret: admin-user-credentials
    metadataDatabase:
      postgresql:
        host: airflow-postgresql
        databaseName: airflow
        credentialsSecret: postgresql-credentials
  webservers:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
  celeryExecutors:
    celeryResultBackend:
      postgresql:
        host: airflow-postgresql
        databaseName: airflow
        credentialsSecret: postgresql-credentials
    celeryBrokerUrl:
      redis:
        host: airflow-redis-master
        credentialsSecret: redis-credentials
    roleGroups:
      default:
        replicas: 1
  schedulers:
    roleGroups:
      default:
        replicas: 1
  dagProcessors:
    roleGroups:
      default:
        replicas: 1
  triggerers:
    roleGroups:
      default:
        replicas: 1
