---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 3.1.5
    pullPolicy: IfNotPresent
  clusterConfig:
    loadExamples: true
    exposeConfig: false
    credentialsSecret: simple-airflow-credentials
  webservers:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
  celeryExecutors:
    roleGroups:
      default:
        replicas: 1
  schedulers:
    roleGroups:
      default:
        replicas: 1
  dagProcessors:
    roleGroups:
      default:
        replicas: 1
  triggerers:
    roleGroups:
      default:
        replicas: 1
