---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 3.1.6
  clusterConfig:
    loadExamples: false
    exposeConfig: false
    credentialsSecret: admin-user-credentials
    metadataDatabase:
      postgresql:
        host: airflow-postgresql
        databaseName: airflow
        credentialsSecret: postgresql-credentials
  webservers:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        envOverrides: &envOverrides
          AIRFLOW_CONN_KUBERNETES_IN_CLUSTER: "kubernetes://?__extra__=%7B%22extra__kubernetes__in_cluster%22%3A+true%2C+%22extra__kubernetes__kube_config%22%3A+%22%22%2C+%22extra__kubernetes__kube_config_path%22%3A+%22%22%2C+%22extra__kubernetes__namespace%22%3A+%22%22%7D"
        replicas: 1
  schedulers:
    roleGroups:
      default:
        envOverrides: *envOverrides
        replicas: 1
  celeryExecutors:
    celeryResultBackend:
      postgresql:
        host: airflow-postgresql
        databaseName: airflow
        credentialsSecret: postgresql-credentials
    celeryBrokerUrl:
      redis:
        host: airflow-redis-master
        credentialsSecret: redis-credentials
    roleGroups:
      default:
        envOverrides: *envOverrides
        replicas: 1
# in case of using kubernetesExecutors
#  kubernetesExecutors:
#    envOverrides: *envOverrides
