---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 3.0.6
  clusterConfig: {}
  webservers:
    roleConfig:
      listenerClass: external-unstable
    envOverrides: &envOverrides
      AIRFLOW__CORE__XCOM_BACKEND: airflow.providers.common.io.xcom.backend.XComObjectStorageBackend
      # The connection id is obtained from the user part of the url that you will provide
      AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_PATH: s3://minio@<bucket-name>/airflow-xcom
      # Any object smaller than the threshold in bytes will be stored in the database and anything larger will be be put in object storage
      AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_THRESHOLD: "1024" # 1KiB
      AIRFLOW__COMMON_IO__XCOM_OBJECTSTORAGE_COMPRESSION: gzip
    roleGroups:
      default:
        replicas: 1
  schedulers:
    envOverrides: *envOverrides
    roleGroups:
      default:
        replicas: 1
  kubernetesExecutors:
    envOverrides: *envOverrides
