apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow
spec:
  image:
    productVersion: 2.9.3
  clusterConfig: {}
  webservers:
    envOverrides: &s3-logging-env-overrides
      AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
      AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: s3://<bucket-name>/airflow-task-logs/
      # The name / connection ID created in the Airflow Web UI
      AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: minio
    roleGroups:
      default:
        replicas: 1
  schedulers:
    envOverrides: *s3-logging-env-overrides
    roleGroups:
      default:
        replicas: 1
  kubernetesExecutors:
    envOverrides: *s3-logging-env-overrides
