#!/usr/bin/env python
"""Assert that Airflow task logs reach the Vector aggregator.

The Vector agent config generated by the operator defines exactly three file sources, each of them
one directory level deep with a fixed suffix:

    ${LOG_DIR}/*/*.stdout.log
    ${LOG_DIR}/*/*.stderr.log
    ${LOG_DIR}/*/*.py.json

Airflow writes a task-attempt log to

    <base_log_folder>/dag_id=<dag>/run_id=<run>/task_id=<task>/attempt=<n>.log

which is four levels deep and, from Airflow 3.1 on, below `$AIRFLOW_HOME/logs` instead of
`${LOG_DIR}` (= /stackable/log). Neither the depth nor the suffix can be matched by any of the
three globs, so task logs are never forwarded to the aggregator - no matter which Airflow version
is used or whether Vector aggregation is enabled.

The task logs checked here belong to the `example_trigger_target_dag` run that step 52 triggers.
The calling test step has already asserted that the worker wrote the attempt logs, so a zero event
count here means the files are there but no Vector source picks them up.
"""

import json
import subprocess
import sys
import time

# Filters events whose file name looks like a task attempt log, see the transform of that name in
# airflow-vector-aggregator-values.yaml.j2.
TRANSFORM = "filteredWorkerTaskLogs"

# Vector rescans its source globs periodically (`glob_minimum_cooldown_ms`, 60s by default), so the
# attempt log being on disk does not mean it has been read yet.
TIMEOUT = 180
INTERVAL = 10


def sent_events(component_id: str) -> int | None:
    """Return the number of events the given component sent, or None if it does not exist."""
    response = subprocess.run(
        [
            "grpcurl",
            "-plaintext",
            "-d",
            '{"limit": 100}',
            "airflow-vector-aggregator:8686",
            "vector.observability.v1.ObservabilityService/GetComponents",
        ],
        capture_output=True,
        text=True,
        check=True,  # Raise a CalledProcessError if non-zero return
        timeout=20,  # seconds
    )
    for component in json.loads(response.stdout).get("components", []):
        if component.get("componentId") == component_id:
            return int(component["metrics"]["sentEventsTotal"] or 0)
    return None


def check_task_logs_are_aggregated() -> None:
    deadline = time.time() + TIMEOUT
    while True:
        events = sent_events(TRANSFORM)
        if events is None:
            sys.exit(f'The aggregator has no transform "{TRANSFORM}".')
        if events > 0:
            print(f"{events} task log events reached the aggregator.")
            return
        if time.time() >= deadline:
            break
        time.sleep(INTERVAL)

    sys.exit(
        f"No task log event reached the aggregator within {TIMEOUT}s although the worker wrote "
        "the attempt log (see the output of the previous command). The Vector agent config "
        "generated by the operator has no file source matching the task log directory tree, so "
        "task logs are silently left out of log aggregation."
    )


if __name__ == "__main__":
    check_task_logs_are_aggregated()
    print("Test successful!")
