= Service exposition with ListenerClasses
:description: Configure Airflow service exposure with ListenerClasses: cluster-internal, external-unstable, or external-stable.

The operator deploys a xref:listener-operator:listener.adoc[Listener] for each Scheduler, Webserver and (Celery-)Worker pod.
They all default to only being accessible from within the Kubernetes cluster, but this can be changed by setting `.spec.{schedulers,celeryExecutors,webservers}.config.listenerClass`:

[source,yaml]
----
spec:
  schedulers:
    config:
      listenerClass: external-unstable  # <1>
  webservers:
    config:
      listenerClass: external-unstable
  celeryExecutors:
    config:
      listenerClass: external-unstable
----
<1> Specify one of `external-stable`, `external-unstable`, `cluster-internal` (the default setting is `cluster-internal`).
This can be set separately for all three roles (but not for kuberneetesExecutors as the resulting worker pods are temporary).

Externally-reachable endpoints (i.e. where listener-class = `external-unstable` or `external-unstable`) are written to a ConfigMap called `<airflow-cluster-name>`, listing each rolegroup by replica.
Both the http and metrics ports are exposed:

[source,yaml]
----
apiVersion: v1
data:
  airflow-scheduler-default-0.metrics: 172.19.0.5:30589
  airflow-webserver-default-0.http: 172.19.0.3:31891
  airflow-webserver-default-0.metrics: 172.19.0.3:30414
  airflow-worker-default-0.metrics: 172.19.0.5:30371
  airflow-worker-default-1.metrics: 172.19.0.3:30514
kind: ConfigMap
...
----
