= Mounting DAGs
:description: Mount DAGs in Airflow via ConfigMap for single DAGs or use git-sync for multiple DAGs. git-sync pulls from a Git repo and handles updates automatically.
:git-sync: https://github.com/kubernetes/git-sync/tree/v4.2.4

DAGs can be mounted by using a ConfigMap or `git-sync`.
This is best illustrated with an example of each, shown in the sections below.

== Via ConfigMap

[source,python]
----
include::example$example-configmap.yaml[]
----
----
include::example$example-airflow-dags-configmap.yaml[]
----
<1> The name of the ConfigMap
<2> The name of the DAG (this is a renamed copy of the `example_bash_operator.py` from the Airflow examples)
[source,yaml]
<3> The volume backed by the ConfigMap
<4> The name of the ConfigMap referenced by the Airflow cluster
<5> The name of the mounted volume
<6> The path of the mounted resource. Note that should map to a single DAG.
<7> The resource has to be defined using `subPath`: this is to prevent the versioning of ConfigMap elements which may cause a conflict with how Airflow propagates DAGs between its components.
<8> If the mount path described above is anything other than the standard location (the default is `$AIRFLOW_HOME/dags`), then the location should be defined using the relevant environment variable.

[WARNING]
--
If a DAG mounted via ConfigMap consists of modularized files, Python uses this as a "root" directory when looking for referenced files.
If this is the case, then either the standard DAGs location should be used, or `PYTHONPATH` should be overriden to point to the new location (it is also necessary to include the logging configuration in the path) as shown below:
[source,yaml]
----
    envOverrides: &envOverrides
      AIRFLOW__CORE__DAGS_FOLDER: "/dags"
      PYTHONPATH: "/stackable/app/log_config:/dags"
----
--

The advantage of this approach is that DAGs are provided "in-line".
However, handling multiple DAGs this way becomes cumbersome, as each must be mapped individually.
For multiple DAGs, it is easier to expose them via `gitsync`, as shown below.

== Via `git-sync`

{git-sync}[git-sync] is a command that pulls a git repository into a local directory and is supplied as a sidecar container for use within Kubernetes.
The Stackable Airflow images already ship with git-sync included, and the operator takes care of calling the tool and mounting volumes, so that only the repository and synchronization details are required:

.git-sync usage example: https
[source,yaml]
----
include::example$example-airflow-gitsync-https.yaml[]
----

<1> A Secret used for accessing database and admin user details (included here to illustrate where different credential secrets are defined)
<2> The git-gync configuration block that contains list of git-sync elements
<3> The repository to clone (required)
<4> The branch name (defaults to `main`)
<5> The location of the DAG folder, relative to the synced repository root.
    It can optionally start with `/`, however, no trailing slash is recommended.
    An empty string (``) or slash (`/`) corresponds to the root folder in Git.
    Defaults to "/".
<6> The depth of syncing i.e. the number of commits to clone (defaults to 1)
<7> The synchronisation interval in seconds, e.g. `20s` or `1h` (defaults to "20s")
<8> The name of the Secret used to access the repository if it is not public.
    This should include two fields: `user` and `password` (which can be either a password -- which is not recommended -- or a GitHub token, as described https://github.com/kubernetes/git-sync/tree/v3.6.4#flags-which-configure-authentication[here])
<9> A map of optional configuration settings that are listed in https://github.com/kubernetes/git-sync/tree/v4.2.1?tab=readme-ov-file#manual[this] configuration section (and the ones that follow on that link)
<10> An example showing how to specify a target revision (the default is HEAD).
     The revision can also be a tag or a commit, though this assumes that the target hash is contained within the number of commits specified by `depth`.
     If a tag or commit hash is specified, then git-sync recognizes this and does not perform further cloning.
<11> Git-sync settings can be provided inline, although some of these (`--dest`, `--root`) are specified internally in the operator and are ignored if provided by the user.
     Git-config settings can also be specified, although a warning is logged if `safe.directory` is specified as this is defined internally, and should not be defined by the user.

.git-sync usage example: ssh
[source,yaml]
----
include::example$example-airflow-gitsync-ssh.yaml[]
----

<1> The name of the Secret used to access the repository if it is not public.
    This should include two fields: `key` and `knownHosts`, both of which can contain multiple entries.
<2> The secret referenced above.

IMPORTANT: Gitsync will not allow both `credentialsSecret` and `sshSecret` to be declared and the operator will throw an exception if this is attempted.

NOTE: git-sync can be used with DAGs that make use of Python modules, as Python is configured to use the git-sync target folder as the "root" location when looking for referenced files.
See the xref:usage-guide/applying-custom-resources.adoc[] example for more details.
