---
apiVersion: batch/v1
kind: Job
metadata:
  name: assert-dags
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: external-dags
          persistentVolumeClaim:
            claimName: pvc-airflow
      containers:
        - name: assert-dags
          image: docker.stackable.tech/stackable/tools:0.2.0-stackable0
          env:
            - name: DEST_DIR
              value: "/stackable/externals"
          command: ["bash", "-x", "-c", "ls -ltr $DEST_DIR"]
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: external-dags
              mountPath: /stackable/externals