# helm install secret-operator oci://oci.stackable.tech/sdp-charts/secret-operator
# helm install commons-operator oci://oci.stackable.tech/sdp-charts/commons-operator
# helm install listener-operator oci://oci.stackable.tech/sdp-charts/listener-operator
# helm install airflow-operator oci://oci.stackable.tech/sdp-charts/airflow-operator
# helm install --repo https://charts.bitnami.com/bitnami --version 12.1.5 --set auth.username=airflow --set auth.password=airflow --set auth.database=airflow --set image.repository=bitnamilegacy/postgresql --set volumePermissions.image.repository=bitnamilegacy/os-shell --set metrics.image.repository=bitnamilegacy/postgres-exporter --set global.security.allowInsecureImages=true airflow-postgresql postgresql
# helm install --repo https://charts.bitnami.com/bitnami --version 17.3.7 --set auth.password=redis --set replica.replicaCount=1 --set global.security.allowInsecureImages=true --set image.repository=bitnamilegacy/redis --set sentinel.image.repository=bitnamilegacy/redis-sentinel --set metrics.image.repository=bitnamilegacy/redis-exporter --set volumePermissions.image.repository=bitnamilegacy/os-shell --set kubectl.image.repository=bitnamilegacy/kubectl --set sysctl.image.repository=bitnamilegacy/os-shell airflow-redis redis
# Log in with user01/user01 or user02/user02
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: openldap-tls
spec:
  backend:
    autoTls:
      ca:
        autoGenerate: true
        secret:
          name: openldap-tls-ca
          namespace: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  serviceName: openldap
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnamilegacy/openldap:2.5
          env:
            - name: LDAP_ADMIN_USERNAME
              value: admin
            - name: LDAP_ADMIN_PASSWORD
              value: admin
            - name: LDAP_USERS
              value: user01,user02
            - name: LDAP_PASSWORDS
              value: user01,user02
            - name: LDAP_ENABLE_TLS
              value: "yes"
            - name: LDAP_TLS_CERT_FILE
              value: /tls/tls.crt
            - name: LDAP_TLS_KEY_FILE
              value: /tls/tls.key
            - name: LDAP_TLS_CA_FILE
              value: /tls/ca.crt
          ports:
            - name: tls-ldap
              containerPort: 1636
          volumeMounts:
            - name: tls
              mountPath: /tls
      volumes:
        - name: tls
          csi:
            driver: secrets.stackable.tech
            volumeAttributes:
              secrets.stackable.tech/class: openldap-tls
              secrets.stackable.tech/scope: pod
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  ports:
    - name: tls-ldap
      port: 636
      targetPort: tls-ldap
  selector:
    app.kubernetes.io/name: openldap
---
apiVersion: authentication.stackable.tech/v1alpha1
kind: AuthenticationClass
metadata:
  name: airflow-with-ldap-server-veri-tls-ldap
spec:
  provider:
    ldap:
      hostname: openldap.default.svc.cluster.local
      port: 636
      searchBase: ou=users,dc=example,dc=org
      ldapFieldNames:
        uid: uid
      bindCredentials:
        secretClass: airflow-with-ldap-server-veri-tls-ldap-bind
      tls:
        verification:
          server:
            caCert:
              secretClass: openldap-tls
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: airflow-with-ldap-server-veri-tls-ldap-bind
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-with-ldap-server-veri-tls-ldap-bind
  labels:
    secrets.stackable.tech/class: airflow-with-ldap-server-veri-tls-ldap-bind
stringData:
  user: cn=admin,dc=example,dc=org
  password: admin
---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-with-ldap-server-veri-tls-credentials
type: Opaque
stringData:
  adminUser.username: airflow
  adminUser.firstname: Airflow
  adminUser.lastname: Admin
  adminUser.email: airflow@airflow.com
  adminUser.password: airflow
  connections.sqlalchemyDatabaseUri: postgresql+psycopg2://airflow:airflow@airflow-postgresql.default.svc.cluster.local/airflow
  # Only needed when using celery workers (instead of Kubernetes executors)
  connections.celeryResultBackend: db+postgresql://airflow:airflow@airflow-postgresql.default.svc.cluster.local/airflow
  connections.celeryBrokerUrl: redis://:redis@airflow-redis-master:6379/0
---
apiVersion: airflow.stackable.tech/v1alpha1
kind: AirflowCluster
metadata:
  name: airflow-with-ldap-server-veri-tls
spec:
  image:
    productVersion: 3.0.6
  clusterConfig:
    loadExamples: true
    exposeConfig: true
    credentialsSecret: airflow-with-ldap-server-veri-tls-credentials
    authentication:
      - authenticationClass: airflow-with-ldap-server-veri-tls-ldap
        userRegistrationRole: Admin
  webservers:
    roleConfig:
      listenerClass: external-unstable
    roleGroups:
      default:
        replicas: 1
  celeryExecutors:
    roleGroups:
      default:
        replicas: 1
  schedulers:
    roleGroups:
      default:
        replicas: 1
