#!/bin/env python
# vim: filetype=python syntax=python tabstop=4 expandtab

import argparse
import logging
import os
import shutil
import sys
import subprocess
import tempfile

__version__ = "0.0.1"


class TestRunnerException(Exception):
    pass


def parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse command line args."""
    parser = argparse.ArgumentParser(description="Run integration tests.")
    parser.add_argument(
        "--version",
        help="Display application version",
        action="version",
        version=f"%(prog)s {__version__}",
    )

    parser.add_argument(
        "--skip-delete",
        help="Do not delete test namespaces.",
        action="store_true",
    )

    parser.add_argument(
        "--skip-release",
        help="Do not install operators.",
        action="store_true",
    )

    parser.add_argument(
        "--parallel",
        help="How many tests to run in parallel. Default 2.",
        type=int,
        required=False,
        default=2,
    )

    parser.add_argument(
        "--operator",
        help="Patch operator version in release.yaml. Format <operator>=<version>",
        nargs="*",
        type=cli_parse_operator_args,
    )

    parser.add_argument(
        "--test",
        help="Kuttl test to run.",
        type=str,
        required=False,
    )

    parser.add_argument(
        "--test-suite",
        help="Name of the test suite to expand. Default: default",
        type=str,
        required=False,
    )

    parser.add_argument(
        "--log-level",
        help="Set log level.",
        type=cli_log_level,
        required=False,
        default=logging.INFO,
    )

    return parser.parse_args(argv)


def cli_parse_operator_args(args: str) -> tuple[str, str]:
    if "=" not in args:
        raise argparse.ArgumentTypeError(
            f"Invalid operator argument: {args}. Must be in format <operator>=<version>"
        )
    op, version = args.split("=", maxsplit=1)
    return (op, version)


def cli_log_level(cli_arg: str) -> int:
    match cli_arg:
        case "debug":
            return logging.DEBUG
        case "info":
            return logging.INFO
        case "error":
            return logging.ERROR
        case "warning":
            return logging.WARNING
        case "critical":
            return logging.CRITICAL
        case _:
            raise argparse.ArgumentTypeError("Invalid log level")


def have_requirements() -> None:
    commands = [
        ("beku", "https://github.com/stackabletech/beku.py"),
        (
            "stackablectl",
            "https://github.com/stackabletech/stackable-cockpit/blob/main/rust/stackablectl/README.md",
        ),
        ("kubectl", "https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/"),
        ("kubectl-kuttl", "https://kuttl.dev/"),
    ]

    err = False
    for command, url in commands:
        if not shutil.which(command):
            logging.error(f'Command "{command}" not found, please install from {url}')
            err = True
    if err:
        raise TestRunnerException()


def maybe_patch_release(operators: list[tuple[str, str]] = []) -> str:
    release_file = os.path.join(
        os.path.dirname(sys.argv[0]), "..", "tests", "release.yaml"
    )
    if not operators:
        logging.debug("No operators to patch")
        return release_file
    # Make a copy so we can mutate it without affecting the original
    ops_copy = operators.copy()
    patched_release = []
    with open(release_file, "r") as f:
        patch_version = ""
        for line in f:
            if patch_version:
                line = line.replace("0.0.0-dev", patch_version)
                patch_version = ""
            else:
                for op, version in ops_copy:
                    if op in line:
                        patch_version = version
                        ops_copy.remove((op, version))
                        break
            patched_release.append(line)
    if ops_copy:
        logging.error(
            f"Operators {', '.join([op for op, _ in ops_copy])} not found in release.yaml"
        )
        raise TestRunnerException()
    with tempfile.NamedTemporaryFile(
        mode="w", delete=False, delete_on_close=False
    ) as f:
        pcontents = "".join(patched_release)
        logging.debug(f"Writing patched release to {f.name}: {pcontents}\n")
        f.write(pcontents)
        return f.name


def maybe_install_release(skip_release: bool, release_file: str) -> None:
    if skip_release:
        logging.debug("Skipping release installation")
        return
    logging.debug(
        f"Installing release: stackablectl release install --release-file {release_file} tests"
    )
    try:
        subprocess.run(
            [
                "stackablectl",
                "release",
                "install",
                "--release-file",
                release_file,
                "tests",
            ],
            check=True,
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Failed to install release: {e.stderr}")
        raise TestRunnerException()


def gen_tests(test_suite: str) -> None:
    try:
        beku_cmd = ["beku"]
        if test_suite:
            beku_cmd.extend(["--suite", test_suite])

        logging.debug(f"Generating tests : {beku_cmd}")
        subprocess.run(
            beku_cmd,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Failed to generate tests: {e.stderr}")
        raise TestRunnerException()


def run_tests(test: str, parallel: int) -> None:
    try:
        kuttl_cmd = ["kubectl-kuttl", "test"]
        if test:
            kuttl_cmd.extend(["--test", test])
        if parallel:
            kuttl_cmd.extend(["--parallel", str(parallel)])
        logging.debug(f"Running tests: {kuttl_cmd}")
        subprocess.run(
            kuttl_cmd,
            check=True,
        )
    except subprocess.CalledProcessError as e:
        logging.error(f"Failed to run tests: {e.stderr}")
        raise TestRunnerException()


def main(argv) -> int:
    ret = 0
    try:
        opts = parse_args(argv[1:])
        logging.basicConfig(encoding="utf-8", level=opts.log_level)
        have_requirements()
        gen_tests(opts.test_suite)
        release_file = maybe_patch_release(opts.operator)
        maybe_install_release(opts.skip_release, release_file)
        run_tests(opts.test, opts.parallel)
    except TestRunnerException:
        ret = 1
    return ret


if __name__ == "__main__":
    sys.exit(main(sys.argv))
