---
name: Integration Test

env:
  DEFAULT_TEST_PLATFORM: kind-1.31.0
  DEFAULT_TEST_ARCHITECTURE: amd64
  DEFAULT_TEST_RUN: all
  DEFAULT_TEST_PARAMETER: "" # Unused when the test-run is 'all'

on:
  # schedule:
    # At 00:00 on Sunday. See: https://crontab.guru/#0_0_*_*_0
    # - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      test-mode:
        description: Test mode
        required: true
        type: choice
        options:
          - custom
          - profile
      test-mode-input:
        description: The profile or the runner used
        required: true
      test-suite:
        description: Name of the test-suite. Only used if test-mode is `custom`
      test:
        description: Name of the test. Only used of test-mode is `custom`

jobs:
  test:
    name: Run Integration Test
    runs-on: ubuntu-latest
    services:
      otel-collector:
        image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s:0.131.1
        volumes:
          - .:/mnt
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          persist-credentials: false
          submodules: recursive

      # TODO: Enable the scheduled runs which hard-code what profile to use
      - name: Run Integration Test
        id: test
        uses: stackabletech/actions/run-integration-test@ad167a759aa0380aab276c0f96382476d62c51c6 # TODO: Use released version
        with:
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          test-mode-input: ${{ inputs.test-mode-input }}
          test-suite: ${{ inputs.test-suite }}
          test-mode: ${{ inputs.test-mode }}
          test: ${{ inputs.test }}

      - name: Send Notification
        if: ${{ failure() || github.run_attempt > 1 }}
        uses: stackabletech/actions/send-slack-notification@ad167a759aa0380aab276c0f96382476d62c51c6 # TODO: Use released version
        with:
          slack-token: ${{ secrets.SLACK_CONTAINER_IMAGE_TOKEN }}
          failed-tests: ${{ steps.test.outputs.failed-tests }}
          test-health: ${{ steps.test.outputs.health }}
          test-result: ${{ steps.test.conclusion }}
          channel-id: C07UYJYSMSN # notifications-integration-tests
          type: integration-test
        # env:
        #   SLACK_BOT_TOKEN: ${{ secrets.SLACK_INTEGRATION_TEST_TOKEN }}
        # uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        # with:
        #   channel-id: "C07UYJYSMSN" # notifications-integration-tests
        #   payload: |
        #       {
        #         "text": "Integration Test for *${{ github.repository }}* failed",
        #         "attachments": [
        #           {
        #             "pretext": "Started at ${{ steps.test.outputs.start-time }}, failed at ${{ steps.test.outputs.end-time }}",
        #             "color": "#aa0000",
        #             "actions": [
        #               {
        #                 "type": "button",
        #                 "text": "Go to integration test run",
        #                 "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        #               }
        #             ]
        #           }
        #         ]
        #       }
