---
name: Integration Test

env:
  DEFAULT_TEST_PLATFORM: kind-1.31.0
  DEFAULT_TEST_ARCHITECTURE: amd64
  DEFAULT_TEST_RUN: all
  DEFAULT_TEST_PARAMETER: "" # Unused when the test-run is 'all'

on:
  # schedule:
    # At 00:00 on Sunday. See: https://crontab.guru/#0_0_*_*_0
    # - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  test:
    name: Run Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: recursive

      - name: Run Integration Test
        id: test
        uses: stackabletech/actions/run-integration-test@990f74b08b1c3693fb80814c20c44a97531ebf75 # TODO: Use released version
        with:
          replicated-api-token: ${{ secrets.REPLICATED_API_TOKEN }}
          test-profile: schedule

      - name: Send Notification
        if: ${{ failure() }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_INTEGRATION_TEST_TOKEN }}
        uses: slackapi/slack-github-action@37ebaef184d7626c5f204ab8d3baff4262dd30f0 # v1.27.0
        with:
          channel-id: "C07UYJYSMSN" # notifications-integration-tests
          payload: |
              {
                "text": "Integration Test *${{ github.repository }}* failed",
                "attachments": [
                  {
                    "pretext": "Started at ${{ steps.test.outputs.start-time }}, failed at ${{ steps.test.outputs.end-time }}",
                    "color": "#aa0000",
                    "actions": [
                      {
                        "type": "button",
                        "text": "Go to integration test run",
                        "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                      }
                    ]
                  }
                ]
              }
